### PR TITLE
[DCK] Remove builtin whitelist proxies from test

### PR DESCRIPTION
**Pull request by yajo**
Apply https://github.com/Tecnativa/doodba/pull/165 in scaffolding. See it for details.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
What happens if you don't create `globalwhitelist_shared`? Maybe should we have a global-scaffolding project too?

**Comment by yajo** [comment]
> What happens if you don't create globalwhitelist_shared?

See https://github.com/Tecnativa/doodba/issues/67#issuecomment-415740216



> Maybe should we have a global-scaffolding project too?

It would be good, although I'm more on the side of dropping some roles into https://galaxy.ansible.com/ to enable full server pool management.

In any case, it's not ready for disclosure.

**Comment by pedrobaeza** [comment]
Well, I miss that also for SSL traefik proxy, so complete the system with the things you see more convenient (roles, scaffolding...).

**Comment by yajo** [comment]
I'll add that to my todo list.

**Comment by pedrobaeza** [comment]
I'm thinking that we should leave one commented example in the scaffolding for easier reference when we need local whitelist. Do you agree?

**Comment by yajo** [comment]
I don't think so; `devel.yaml` still has whitelists, and in case you want to document things, the place to do so is the documentation, not the scaffolding, which is just a template. The docs are in https://github.com/Tecnativa/doodba#how-can-i-whitelist-a-service-and-allow-external-access-to-it and https://github.com/Tecnativa/docker-whitelist.

**Pull request merged**
