### PR TITLE
delete old style S3 URI

### PR DESCRIPTION
**Pull request by yelizariev**
See https://forums.aws.amazon.com/ann.jspa?annID=6776

Also, it allows to specify folder and custom S3 provider (e.g. https://github.com/minio/minio)

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I don't know about this, so when my colleague @Yajo comes from holidays, he will take a look.

**Comment by yajo** [comment]
It's true that this variable would be more helpful this way. Actually, we should just define the full DST path, including protocol, as you might prefer to store backups in webdav, sftp or other backends.

This stays here as a remainder of times before #24, where other AWS-only variables were defined in the `.env` file too.

However, this line must be changed in every deployment out there, so this change means that we have 100% chance of getting a non-obvious git conflict on next scaffolding update.

I've got in my roadmap switching to [Copier](https://github.com/pykong/copier) to handle the scaffolding. This can be better fixed in that point, so I avoid annoying scaffolding users (including myself :stuck_out_tongue:) for this semi-cosmetic change.

In the mean time, you can add this change to your downstream scaffolding. Let me close this PR. If you want, you can open an issue about this, so I don't forget to handle it when we move to Copier.

Thanks for the contribution, though!

**Comment by yajo** [comment]
Oh sorry I missed the point about S3 path deprecation.

Would you mind please fixing just that, without touching the `.env` file?

Thanks!

**Comment by yelizariev** [comment]
I made a new PR to update S3 URI only: #62 

About full DST.
I'm not sure how it's possible to organize scaffolding to allow any DST: each of them requires different credentials and probably different duplicity image.

About ``.env``.
I thought that scaffolding is just a first version of a custom project and it's not something to merge to the custom project from time to time :thinking:

**Comment by yajo** [comment]
> each of them requires different credentials and probably different duplicity image

It could be, but it's also true that the fact you can change the protocol seems more understandable when you see it at first sight. And in those cases you describe, you change less lines.



>  I thought that scaffolding is just a first version of a custom project and it's not something to merge to the custom project from time to time thinking

You can use it as you prefer, but we often update our scaffoldings and recommend that, to benefit from latest features. Also, there are some breaking changes from time to time as you might have seen in https://github.com/Tecnativa/doodba/issues/67 which affect the scaffolding.

The move to copier will help with that too, as we're adding updates support to the tool.

**Pull request closed without merging**
